spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/config-repo

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
