server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET:defaultBase64Secret}
  accessExpiration: 3600000
  refreshExpiration: 86400000
  serviceExpiration: 7200000
