server:
  port: 8082
  ssl:
    enabled: true
    key-store: classpath:taskflow.p12
    key-store-type: PKCS12
    key-store-password: taskapp
spring:
  # DataSource Configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/task_service
    username: taskflow_user
    password: taskflow_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 20000

  # R2DBC (if you’re using reactive)
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/task_service
    username: taskflow_user
    password: taskflow_pass

  # Flyway Migrations
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true

  # JWT Configuration (centralized)
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET:defaultBase64Secret}
          accessExpiration: 3600000
          refreshExpiration: 86400000
          serviceExpiration: 7200000

# Eureka Configuration (kept for consistency)
eureka:
  client:
    service-url:
      defaultZone: https://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    io.r2dbc.postgresql: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive: DEBUG
    com.venky.task_service: DEBUG
