server:
  port: 8082

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://postgres:5432/task_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
